float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant
    run_groups:
      default:
        args: [
          ['none', 'scalar', 'binary'], #quantization
          # ['none'], #quantization
          [ 16, 32, 48, 72 ], #m
          # [ 16 ], #m
          [ 64, 100, 128, 256, 512 ], #ef_construct
          # [ 100 ], #ef_construct
        ]
        query_args: [
          [null, 8, 16, 32, 40, 64, 128, 256, 512, 768], #hnsw_ef
          # [40], #hnsw_ef
          [True, False], # re-score
          # [False], # re-score
        ]
