float:
  angular:
  - base_args: []
    constructor: ChromaBase
    disabled: false
    docker_tag: ann-benchmarks-chroma
    module: ann_benchmarks.algorithms.chroma
    name: chroma
    run_groups:
      default:
        args: []
        query_args: []