float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusFLAT
      disabled: true
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-flat
      run_groups:
        FLAT:
          args:
            placeholder: [0]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFFLAT
      disabled: true
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfflat
      run_groups:
        IVFFLAT:
          args:
            # nlist: [128, 256, 512, 1024, 2048, 4096]
            nlist: [512]
          # query_args: [[1, 10, 20, 50, 100]]
          query_args: [[10]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFSQ8
      disabled: true
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfsq8
      run_groups:
        IVFSQ8:
          args:
            # nlist: [128, 256, 512, 1024, 2048, 4096]
            nlist: [512]
          # query_args: [[1, 10, 20, 50, 100]]
          query_args: [[10]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFPQ
      disabled: true
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfpq
      run_groups:
        IVFPQ:
          args:
            # nlist: [128, 256, 512, 1024, 2048, 4096]
            nlist: [512]
            # m: [2, 4]
            m: [2]
          # query_args: [[1, 10, 20, 50, 100]]
          query_args: [[10]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw
      run_groups:
        HNSW:
          args:
            M: [4, 8, 12, 16, 24, 36, 48, 64, 96]
            # M: [16]
            efConstruction: [100, 200, 500]
            # efConstruction: [100]
          query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]] # ef
          # query_args: [[40]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusSCANN
      disabled: true
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-scann
      run_groups:
        SCANN:
          args:
            # nlist: [64, 128, 256, 512, 1024, 2048, 4096, 8192]
            nlist: [512]
          # query_args: [[1, 10, 20, 30, 50]]
          query_args: [[10]]
